---
title: "EDA Final Project"
author: "SMiltonDZouGKhalsa"
date: "2022-11-22"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Set-up Data Set

```{r}

library(rvest)
library(tidyverse)
library(ggplot2)
library (lubridate)

```



## Input Data


```{r, echo = FALSE}

#Import NY Covid data (March 1, 2020 to November 22, 2022)

ny_covid_dat <- read_html('https://health.data.ny.gov/Health/New-York-State-Statewide-COVID-19-Testing/xdss-u53e/explore/query/SELECT%0A%20%20%60county%60%2C%0A%20%20sum%28%60new_positives%60%29%20AS%20%60sum_new_positives%60%2C%0A%20%20sum%28%60cumulative_number_of_positives%60%29%20AS%20%60sum_cumulative_number_of_positives%60%2C%0A%20%20sum%28%60total_number_of_tests%60%29%20AS%20%60sum_total_number_of_tests%60%2C%0A%20%20sum%28%60cumulative_number_of_tests%60%29%20AS%20%60sum_cumulative_number_of_tests%60%2C%0A%20%20median%28%60test_positive%60%29%20AS%20%60median_test_positive%60%0AGROUP%20BY%20%60county%60/page/aggregate')

ny_covid_dat


#Scrape the data from the website

#Set the element address variables (determined in the previous step)
the_county_tag <- '.not-editable:nth-child(1) div'
the_sum_new_positives_tag <- '.not-editable:nth-child(2) div'
the_sum_cumulative_no_of_positives_tag <- '.not-editable:nth-child(3) div'
the_sum_total_number_tests_tag <- '.not-editable:nth-child(4) div'
the_sum_cumulative_number_tests_tag <- '.not-editable:nth-child(5) div'
the_median_test_positive_tag <- '.not-editable:nth-child(6) div'

#Scrape the data items
the_county <- ny_covid_dat%>% html_nodes(the_county_tag) %>% html_text()
the_sum_cumulative_no_of_positives <- ny_covid_dat %>%   html_nodes(the_sum_cumulative_no_of_positives_tag) %>%  html_text()
the_sum_total_number_tests <- ny_covid_dat %>% html_nodes(the_sum_total_number_tests_tag) %>% html_text()
the_sum_cumulative_number_tests <- ny_covid_dat %>% html_nodes(the_sum_cumulative_number_tests_tag) %>% html_text()
the_median_test_positive_tag <- ny_covid_dat %>% html_nodes(the_median_test_positive_tag) %>% html_text()

## Remove state wide column

#Import NY population data (2022)

ny_pop_dat <- read.csv("./Raw_Data/NY_County_Level_Population_Data.csv")




```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
